### ISSUE TITLE
desktop file puts program in "wrong" category

### ISSUE THREAD

**Issue by Boruch-Baum** [aadityabagga/timeset-gui#2]
I put "wrong" in quotes in the title because there isn't really any right or wrong about this, but the program should be put in the "Settings" category, because in other editions of Manjaro that's where the time settings are made, via program "Manjaro Settings Manager".

**Comment by abchk1234** [comment]
Hmm, you do have a point there :slightly_smiling_face: 

I guess I placed it in `System` to be easily visible, since there are many more entries under `Settings` than under `System`. Let me look into how it looks under `Settings` and I will change it.

**Comment by Boruch-Baum** [comment]
You could also place the program in both categories. Many other programs appear in multiple places in the menu.

**Comment by abchk1234** [comment]
Nah, I think one entry under `Settings` as per your original suggestion should be enough, thx for the report.
