### ISSUE TITLE
Python error on launch @ ArchLinux

### ISSUE THREAD

**Issue by spaceserver** [aadityabagga/timeset-gui#6]
~>$ timeset-gui 
/usr/sbin/timeset-gui:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Traceback (most recent call last):
  File "/usr/sbin/timeset-gui", line 509, in <module>
    win = MainWindow()
  File "/usr/sbin/timeset-gui", line 407, in __init__
    self.set_icon_from_file(program_icon)
AttributeError: 'MainWindow' object has no attribute 'set_icon_from_file'

**Comment by abchk1234** [comment]
Thanks for reporting @spaceserver ! I think GTK4 has deprecated setting icon from file, hence the error.
The solution could be to install the timeset-gui icon in default icon path, and use the `Gtk.Window.set_icon_name` method.
Will check and report back.

**Comment by abchk1234** [comment]
Hi @spaceserver ,

Have pushed a commit that should fix the issue. Could you try it out?
Download the code, and inside it run the program manually:
~~~~
./bin/timeset-gui.py
~~~~

**Comment by spaceserver** [comment]
works like a charm, thx! :)

**Comment by abchk1234** [comment]
Version updated and pushed to AUR few weeks ago.
